# Generated by Django 6.0 on 2025-12-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Identificador')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='URL Imagen')),
                ('external_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link externo')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('archived', 'Archivada')], default='draft', max_length=20, null=True, verbose_name='Estado')),
                ('view_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contador de visitas')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='Creado por')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Actualizado por')),
                ('published_by', models.IntegerField(blank=True, null=True, verbose_name='Publicado por')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_categories',
                'managed': False,
            },
        ),
    ]
